# Build and run the program as default.
default: build run

# Build the application.
build:
	@gcc main.c int_vector.c -o main -Wall -Werror

# Run the application.
run:
	@./main

# Clean the application.
clean:
	@rm -f main