# Build and run the application as default.
default: build run

# Build the application.
build:
	@g++ main.cpp -o main -Wall -Werror

# Run the application.
run:
	@./main

# Clean the application.
clean:
	@rm -f main