# Build and run the application, then remove it.
default: build run clean

# Build the application.
build:
	@g++ main.cpp -o main -Wall -Werror

# Run the application.
run:
	@./main

# Clean the application.
clean:
	@rm -f main
